### ISSUE TITLE
Option diffing against dump only

### ISSUE THREAD

**Issue by Snarkyfork** [NiceneNerd/UKMM#168]
I can't seem to get dialogue changes for mods such as Linkle to show up in game. Right now I am trying to get [Legend of Linkle Dialogue Mod](https://gamebanana.com/mods/439900) to work but not having any luck.

Edit: There are options in the mod, one for Linkles Diary in Impa's house and another for Sleepover with Riju, and both of those options seem to work fine but not he base dialogue for the mod.

**Comment by NiceneNerd** [comment]
Turns out this is an issue with inflating BNPs with options, as in multiple merger categories, including texts, options end up getting diffed so as to undo all changes from the base mod. Shall be getting this fixed swiftly.

**Comment by Snarkyfork** [comment]
That's awesome, thanks!

**Comment by NiceneNerd** [comment]
Fixed in 5843b6

**Comment by OhNoOhNOOO** [comment]
After testing on a build of the latest commit, I think this is still an issue. Screenshot of hierarchy attached in case I'm just doing something wrong.
![Screenshot from 2024-04-28 02-45-56](https://github.com/NiceneNerd/UKMM/assets/107513274/7b10b67a-c658-4c89-b4c1-3f4f57c42c39)

**Comment by NiceneNerd** [comment]
@OhNoOhNOOO Did you uninstall the mod and reinstall it after compiling from the latest source?

**Comment by OhNoOhNOOO** [comment]
Yes, i made sure to rebuild and redeploy with the new executable

**Comment by NiceneNerd** [comment]
Just rebuild and redeploy? Not uninstall the mod and then reinstall it?

**Comment by OhNoOhNOOO** [comment]
retested with uninstalling and reinstalling the dialogue mod, and it still did not work. voices and scenes are changed, but dialogue boxes remain unchanged.

**Comment by NiceneNerd** [comment]
Which options are enabled?

**Comment by OhNoOhNOOO** [comment]
All options are enabled, and I'm using the UKMM download.

**Comment by NiceneNerd** [comment]
The UKMM download won't work, as the error happens during building, and that mod was built while the bug was present in UKMM. Try the BNP.

**Comment by OhNoOhNOOO** [comment]
Using the BMP worked luckily
